# Generated by Django 2.1 on 2018-09-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_signs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_category', models.CharField(max_length=250)),
                ('sign_id', models.CharField(max_length=4)),
                ('sign_name', models.CharField(max_length=250)),
                ('sign_url', models.CharField(max_length=250)),
            ],
        ),
    ]
