# Generated by Django 2.1.1 on 2018-09-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_signs', '0002_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_t',
        ),
    ]
