# Generated by Django 2.1.1 on 2018-09-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_signs', '0003_delete_test_t'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign',
            new_name='sign_all',
        ),
    ]
