# Generated by Django 2.1.1 on 2018-09-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_signs', '0004_auto_20180909_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_all',
            new_name='sign',
        ),
    ]
